version: '3.1'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
    php:
        build: ./php
        volumes:
            - ../src:/var/www/laravel
        environment:
            DB_HOST: db
    nginx:
        build: ./nginx
        volumes:
            - ../src:/var/www/laravel
        ports:
            - "8888:80"
        # environment:
        #     APP_NAME: Laravel
        #     APP_ENV: local
        #     APP_KEY: base64:4cLzfUMtXGNbQZ+gaF/xcST7tMbThXSyV9yjLDwKfkI=
        #     APP_DEBUG: "true"
        #     APP_URL: http://localhost:8888

        #     DB_CONNECTION: mysql
        #     DB_HOST: 127.0.0.1
        #     DB_PORT: 3306
        #     DB_DATABASE: homestead
        #     DB_USERNAME: homestead
        #     DB_PASSWORD: secret

        #     BROADCAST_DRIVER: log
        #     CACHE_DRIVER: file
        #     QUEUE_CONNECTION: sync
        #     SESSION_DRIVER: file
        #     SESSION_LIFETIME: 120

        #     MAIL_DRIVER: smtp
        #     MAIL_HOST: smtp.mailtrap.io
        #     MAIL_PORT: 2525
        #     MAIL_USERNAME: null
        #     MAIL_PASSWORD: null
        #     MAIL_ENCRYPTION: null
    